services:
  - type: web
    name: shl-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: chroma_db
      mountPath: /data/chroma_db
      sizeGB: 1

  - type: web
    name: shl-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=10000 --server.address=0.0.0.0
    plan: free
    envVars:
      - key: BACKEND_URL
        value: https://shl-backend.onrender.com
    disk:
      name: chroma_db
      mountPath: /data/chroma_db
      sizeGB: 1